add rake task, add component path to not found
OpenSourcePolitics/decidim-module_homepage_proposals pull request #10
Opened 2023-06-13 09:44 UTC by eliegaboriau

2023-06-13 12:22 UTC, Quentinchampenois requested changes
Just a little change request otherwise it seems good to me !

2023-06-13 12:22 UTC, Quentinchampenois commented on app/controllers/decidim/proposals_slider_controller.rb
> +      { url: main_component_path(Decidim::Component.find(params.dig(:filter, :component_id))) }
We should prevent ActiveRecord::NotFound exception using a try / catch or guard clause

2023-06-13 12:54 UTC, AyakorK approved these changes

2023-06-16 08:41 UTC, Quentinchampenois approved these changes

2023-06-16 08:41 UTC, merged