Backport Proposal filters
OpenSourcePolitics/decidim-module_homepage_proposals pull request #39
Opened 2024-05-22 13:11 UTC by alecslupu

2024-05-22 23:12 UTC, simonaszilinskas commented
![Export-1716419527906](https://github.com/OpenSourcePolitics/decidim-module_homepage_proposals/assets/14858948/f230e4e7-86cf-42b9-a157-1522a31b1c15)

Tested and works perfectly well

2024-05-31 11:03 UTC, moustachu approved these changes

2024-05-31 11:47 UTC, Quentinchampenois requested changes
Thank you for the PR !

I would like to confirm if version `0.26.10` is a requirement ? Otherwise we should keep the current `self.decidim_version`

2024-05-31 11:47 UTC, Quentinchampenois commented on lib/decidim/homepage_proposals/version.rb
> +      "0.26.10"
```suggestion
      "0.26"
```



Is the 0.26.10 version a requirement ? We currently load it in `*.gemspec` as follow : `s.add_dependency "decidim-core", "~> #{Decidim::HomepageProposals.decidim_version}"`

2024-05-31 13:11 UTC, merged