Wip/0.26
OpenSourcePolitics/decidim-module_homepage_proposals pull request #9
Opened 2023-06-08 10:15 UTC by eliegaboriau

2023-06-09 07:58 UTC, Quentinchampenois requested changes
We also need to : 
- Create rake task to load JS dependencie `GlideJS`
- Change ProposalNotFound visit link in template to the default_component url
- Add release CI (maybe in another PR)

2023-06-09 07:58 UTC, Quentinchampenois commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_cell.rb
> +        include Cell::ViewModel::Partial
I guess there is unused includes and methods in this cell, we should cleanup this file and keep only what we need

2023-06-09 07:58 UTC, Quentinchampenois commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_cell.rb
> +          components = Decidim::Component.where(id: content_block_settings.linked_components_id.reject(&:blank?).map(&:to_i))
```suggestion
          components = Decidim::Component.where(id: content_block_settings.linked_components_id.compact.map(&:to_i))
```

`compact` is equivalent to `reject(&:blank?)`.

2023-06-09 07:58 UTC, Quentinchampenois commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_cell.rb
> +          return options_for_select(options, selected: params[:filter][:component_id]) if params[:filter].present? && params[:filter][:component_id].present?
```suggestion
          return options_for_select(options, selected: params.dig(:filter, :component_id) if params.dig(:filter, :component_id).present?
```

2023-06-09 07:58 UTC, Quentinchampenois commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_cell.rb
> +          return options_for_select(options, selected: params[:filter][:component_id]) if params[:filter].present? && params[:filter][:component_id].present?
I just saw similar return clause just after, we should create private method which returns the selected item, the params component_id or the default_linked_component

2023-06-09 07:58 UTC, Quentinchampenois commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_cell.rb
> +          @linked_components ||= Decidim::Component.where(id: content_block_settings.linked_components_id.reject(&:blank?).map(&:to_i))
```suggestion
          @linked_components ||= Decidim::Component.where(id: content_block_settings.linked_components_id.compact.map(&:to_i))
```

To test:  If the `content_block_settings.linked_components_id.compact` returns an Array of ID as String, we probably have not to use `.map(&:to_i)`

2023-06-09 07:58 UTC, Quentinchampenois commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_cell.rb
> +        def default_filter_params
I think `default_filter_params` is not used in Cell

2023-06-09 07:58 UTC, Quentinchampenois commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_settings_form_cell.rb
> +          components = Decidim::Component.where(id: content_block.settings.linked_components_id.reject(&:blank?).map(&:to_i))
```suggestion
          components = Decidim::Component.where(id: content_block.settings.linked_components_id.compact)
```

2023-06-09 07:58 UTC, Quentinchampenois commented on app/controllers/decidim/proposals_slider_controller.rb
> +        category = Decidim::Category.find(params[:filter][:category_id]) if params[:filter][:category_id].present?
```suggestion
        params.dig(:filter, :category_id) if params.dig(:filter, :category_id).present?
```

2023-06-09 07:58 UTC, Quentinchampenois commented on app/controllers/decidim/proposals_slider_controller.rb
> +        scopes = Decidim::Scope.find(params[:filter][:scope_id]) if params[:filter][:scope_id].present?
```suggestion
       params.dig(:filter, :scope_id) if params.dig(:filter, :scope_id).present?
```

2023-06-09 07:58 UTC, Quentinchampenois commented on app/controllers/decidim/proposals_slider_controller.rb
> +                                                         .where(component: params[:filter][:component_id])
```suggestion
 .where(component: params.dig(:filter, :component_id)
```

2023-06-09 07:58 UTC, Quentinchampenois commented on app/packs/src/decidim/homepage_proposals/glidejs/glideItems/Proposal.js
> +        switch(this.state){
Move switch case in a dedicated method

2023-06-09 08:51 UTC, eliegaboriau commented on app/cells/decidim/homepage_proposals/content_blocks/proposals_slider_cell.rb
> +        def default_filter_params
It is, it crashes without

2023-06-12 08:05 UTC, AyakorK approved these changes
LGTM !
 Just a few questions : 
 - Shouldn't we hide the slider if he's activated unless there is a component selected ?
 - Couldn't we add an "auto-scroll" if this is possible to navigate through more proposals ?
 - Should we rework a bit the css of the filters (Actually clear filters is next to the filters which renders something weird)
 - It looks like it is by default activated as a component of the homepage, should we try to change that ?

2023-06-12 09:14 UTC, Quentinchampenois approved these changes

2023-06-12 09:15 UTC, merged